// ═══════════════════════════════════════════════════════════════════════
//  SITE CONFIGURATION  —  edit this file to configure the shop
// ═══════════════════════════════════════════════════════════════════════

const CONFIG = {
  siteName:     "Emma's Lab",
  siteUrl:      'https://emmas-lab.ch', // ← YOUR DOMAIN (no trailing slash)
  contactEmail: 'emmaslabcandle@gmail.com',
  phone:        '+41 78 256 29 52',
  whatsapp:     '41782562952',
  instagram:    'emmas_lab_candle',
  currency:     'CHF',

  // ── EmailJS ─────────────────────────────────────────────────────────
  // Sign up at https://www.emailjs.com, then fill in these three values.
  // Step-by-step instructions are in the README below the CONFIG block.
  emailjs: {
    publicKey:  'fA4Qdc27FVtcfBfhL',
    serviceId:  'service_dfx69bu',
    templateId: 'template_7z11sev',
  },

  // SEO — used in <title>, meta description, og:image etc.
  seo: {
    defaultLang: 'en',
    ogImage: 'https://emmas-lab.ch/images/og-cover.jpg',
  },
};

// ═══════════════════════════════════════════════════════════════════════
//  UI TRANSLATIONS  —  strings used in buttons, labels, nav, etc.
//  To add a language: copy one block, change the key, translate strings.
// ═══════════════════════════════════════════════════════════════════════

const TRANSLATIONS = {
  en: {
    'meta.title':       "Emma's Lab | Painting Kits for Kids Switzerland – Toys, Crafts & Party Activities",
    'meta.description': 'Handmade plaster painting kits for kids in Switzerland. Unicorn & dinosaur sets — perfect educational toy, creative gift, or party activity. Includes paints, brush & instructions. From CHF 7. Order online.',
    'meta.keywords':    'painting kit kids Switzerland, plaster figure painting, educational toy Switzerland, creative gift children, party activity kids, craft for kids, unicorn toy, dinosaur toy, kids birthday activity, handmade toy Switzerland',
    'nav.about':    'About',
    'nav.contact':  'Contact',
    'nav.blog':     'Blog',
    'cart.label':   'Cart',
    'cart.title':   'Cart',
    'cart.empty':   'Your cart is empty.',
    'cart.subtotal':'Subtotal',
    'shop.title':   'Shop',
    'cat.all':      'All',
    'cat.unicorn':  'Unicorn',
    'cat.dinosaur': 'Dinosaur',
    'cat.candle':   'Candle',
    'about.title':  'Meet the Creator',
    'about.p1':     'Hi, I\'m Ekaterina — and creating has been part of my life for as long as I can remember. I studied at art school while growing up, where I learned to see beauty in colors, details, and the little things most people overlook. Since then, making things with my hands became more than a hobby — it became the way I express myself.',
    'about.p2':     'Over the years, I\'ve explored many kinds of creativity: designing handmade rugs, knitting sweaters stitch by stitch, making candles by hand, and constantly finding joy in turning simple materials into something meaningful.',
    'about.p3':     'At one point, I became deeply passionate about artistic makeup and special effects — another form of art to create, transform, and tell stories. In 2019, I was honored to be recognized among the Top 30 makeup artists in my country by NYX Professional Makeup.',
    'about.p4':     'No matter what I create — paint, textiles, candles, or handmade crafts — the feeling is always the same: I love making ordinary moments feel special.',
    'about.p5':     'This shop was born from that feeling. I wanted to create more than just painting kits — small moments of comfort, creativity, and calm. Something that helps people slow down, enjoy the process, and make something beautiful with their own hands.',
    'about.p6':     'Whether you\'re spending a quiet evening alone, looking for a thoughtful gift, or simply wanting to try something new — my hope is that these kits bring warmth, joy, and creativity into your life.',
    'contact.title':'Get in touch',
    'contact.text': 'Questions, custom orders, wholesale inquiries:',
    'contact.label.email': 'Email',
    'contact.label.phone': 'Phone',
    'contact.form.title':   'Send a Message',
    'contact.form.name':    'Name *',
    'contact.form.email':   'Email *',
    'contact.form.message': 'Message *',
    'contact.form.submit':  'Send Message',
    'contact.form.sending': 'Sending…',
    'contact.form.success': '✓ Message sent! We\'ll get back to you shortly.',
    'contact.form.error':   '✕ Something went wrong. Please try again or email us directly.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'All rights reserved.',
    'form.title':   'Send a Request',
    'form.name':    'Name *',
    'form.email':   'Email *',
    'form.phone':   'Phone',
    'form.city':    'City / Postcode',
    'form.address': 'Delivery Address',
    'form.notes':   'Notes / Special requests',
    'form.submit':  'Send Request',
    'form.sending': 'Sending…',
    'form.success': '✓ Your request has been sent! We will contact you shortly.',
    'form.error':   '✕ Something went wrong. Please try again or contact us directly.',
    'add.to.cart':  'Add to Cart',
    'badge.sale':   'Sale',
    'added.toast':  'Added to cart',
    'shipping.ch':   'Shipping within Switzerland: CHF 8',
    'shipping.intl': 'International shipping: rate confirmed in your reply email',
    'hero.eyebrow':  'Handmade in Switzerland',
    'hero.headline': 'Paint Your Own Unicorn or Dinosaur',
    'hero.sub':      'Handmade plaster kits with everything included — just open, paint, and enjoy. Perfect for birthdays, family nights, and creative gifts.',
    'hero.cta':      'See All Kits',
    'pain.intro':    'Sound familiar?',
    'pain.1':        'Looking for a birthday activity the whole group will actually enjoy — not just watch?',
    'pain.2':        'Need a creative gift that stands out from the usual toys and actually gets used?',
    'pain.3':        'Want to spend quality time together and make something with your own hands — without screens?',
    'benefit.title':    'Everything You Need, Right in the Box',
    'benefit.1.title':  'All Included',
    'benefit.1.text':   'Figurine, paints, brush, postcard & stickers — nothing to buy separately',
    'benefit.2.title':  'Open & Paint',
    'benefit.2.text':   'Ready in seconds. No prep, no mess setup, no experience needed',
    'benefit.3.title':  'Handmade in Switzerland',
    'benefit.3.text':   'Each plaster figure is cast by hand with care and attention to detail',
    'benefit.4.title':  'For Groups Too',
    'benefit.4.text':   'Party Box with 10 complete kits — perfect for birthdays and events',
    'partycta.tag':        'Best Value',
    'partycta.title':      'Planning a Party?',
    'partycta.sub':        'Get 10 complete kits in one box for CHF 4.50 each — 35% cheaper than buying separately.',
    'partycta.btn.unicorn':'🦄 Unicorn Party Box',
    'partycta.btn.dino':   '🦕 Dinosaur Party Box',
  },

  fr: {
    'meta.title':       "Emma's Lab | Kits de Peinture pour Enfants Suisse – Jouets, Créativité & Activités Fête",
    'meta.description': 'Kits de peinture en plâtre faits main pour enfants en Suisse. Licornes & dinosaures — jouet éducatif, cadeau créatif ou activité de fête. Avec peintures, pinceau et instructions. Dès CHF 7.',
    'meta.keywords':    'kit peinture enfants Suisse, figurine plâtre à peindre, jouet éducatif Suisse, cadeau créatif enfant, activité anniversaire enfants, loisirs créatifs, jouet licorne, jouet dinosaure, idée cadeau enfant, artisanat enfant Suisse',
    'nav.about':    'À propos',
    'nav.contact':  'Contact',
    'nav.blog':     'Blog',
    'cart.label':   'Panier',
    'cart.title':   'Panier',
    'cart.empty':   'Votre panier est vide.',
    'cart.subtotal':'Sous-total',
    'shop.title':   'Boutique',
    'cat.all':      'Tout',
    'cat.unicorn':  'Licorne',
    'cat.dinosaur': 'Dinosaure',
    'cat.candle':   'Bougie',
    'about.title':  'Rencontrez la Créatrice',
    'about.p1':     "Bonjour, je suis Ekaterina — et la création fait partie de ma vie depuis toujours. J'ai étudié aux beaux-arts dans ma jeunesse, où j'ai appris à voir la beauté dans les couleurs, les détails et les petites choses que la plupart des gens ne remarquent pas. Depuis, créer avec mes mains est devenu bien plus qu'un passe-temps — c'est ma façon de m'exprimer.",
    'about.p2':     "Au fil des années, j'ai exploré de nombreuses formes de créativité : la conception de tapis faits main, le tricot de pulls point par point, la fabrication de bougies artisanales, et la joie constante de transformer des matériaux simples en quelque chose de beau.",
    'about.p3':     "À un moment, je me suis passionnée pour le maquillage artistique et les effets spéciaux — une autre forme d'art pour créer, transformer et raconter des histoires. En 2019, j'ai eu l'honneur d'être reconnue parmi les 30 meilleurs maquilleurs de mon pays par NYX Professional Makeup.",
    'about.p4':     "Peu importe ce que je crée — peinture, textiles, bougies ou artisanat — le sentiment est toujours le même : j'aime rendre les moments ordinaires extraordinaires.",
    'about.p5':     "Cette boutique est née de ce sentiment. Je voulais créer plus que de simples kits de peinture — de petits moments de confort, de créativité et de calme. Quelque chose qui aide les gens à ralentir, à apprécier le processus et à créer quelque chose de beau de leurs propres mains.",
    'about.p6':     "Que vous passiez une soirée tranquille seul, que vous cherchiez un cadeau attentionné, ou que vous souhaitiez simplement essayer quelque chose de nouveau — mon espoir est que ces kits apportent chaleur, joie et créativité dans votre vie.",
    'contact.title':'Contactez-nous',
    'contact.text': 'Questions, commandes personnalisées, ventes en gros :',
    'contact.label.email': 'E-mail',
    'contact.label.phone': 'Téléphone',
    'contact.form.title':   'Envoyer un message',
    'contact.form.name':    'Nom *',
    'contact.form.email':   'E-mail *',
    'contact.form.message': 'Message *',
    'contact.form.submit':  'Envoyer le message',
    'contact.form.sending': 'Envoi…',
    'contact.form.success': '✓ Message envoyé ! Nous vous répondrons sous peu.',
    'contact.form.error':   '✕ Une erreur est survenue. Réessayez ou écrivez-nous directement.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'Tous droits réservés.',
    'form.title':   'Envoyer une demande',
    'form.name':    'Nom *',
    'form.email':   'E-mail *',
    'form.phone':   'Téléphone',
    'form.city':    'Ville / Code postal',
    'form.address': 'Adresse de livraison',
    'form.notes':   'Notes / Demandes spéciales',
    'form.submit':  'Envoyer la demande',
    'form.sending': 'Envoi en cours…',
    'form.success': '✓ Votre demande a été envoyée ! Nous vous contacterons prochainement.',
    'form.error':   '✕ Une erreur est survenue. Veuillez réessayer ou nous contacter directement.',
    'add.to.cart':  'Ajouter au panier',
    'badge.sale':   'Solde',
    'added.toast':  'Ajouté au panier',
    'shipping.ch':   'Livraison en Suisse : CHF 8',
    'shipping.intl': 'Livraison internationale : tarif confirmé dans votre e-mail de réponse',
    'hero.eyebrow':  'Fait main en Suisse',
    'hero.headline': 'Peignez votre propre licorne ou dinosaure',
    'hero.sub':      'Kits en plâtre faits main — tout inclus. Ouvrez la boîte, peignez et profitez. Parfait pour les anniversaires, les soirées en famille et les cadeaux créatifs.',
    'hero.cta':      'Voir les kits',
    'pain.intro':    'Vous vous reconnaissez ?',
    'pain.1':        'Vous cherchez une activité d\'anniversaire que tout le groupe adorera — pas juste regarder ?',
    'pain.2':        'Vous avez besoin d\'un cadeau créatif qui se démarque des jouets habituels et qui sera vraiment utilisé ?',
    'pain.3':        'Vous voulez passer du temps de qualité ensemble et créer quelque chose de vos propres mains — sans écrans ?',
    'benefit.title':    'Tout ce qu\'il faut, dans la boîte',
    'benefit.1.title':  'Tout inclus',
    'benefit.1.text':   'Figurine, peintures, pinceau, carte postale & autocollants — rien à acheter en plus',
    'benefit.2.title':  'Ouvrir & Peindre',
    'benefit.2.text':   'Prêt en quelques secondes. Pas de préparation, pas d\'expérience nécessaire',
    'benefit.3.title':  'Fait main en Suisse',
    'benefit.3.text':   'Chaque figurine en plâtre est coulée à la main avec soin et attention',
    'benefit.4.title':  'Pour les groupes aussi',
    'benefit.4.text':   'Party Box avec 10 kits complets — parfait pour les anniversaires et événements',
    'partycta.tag':        'Meilleure offre',
    'partycta.title':      'Vous organisez une fête ?',
    'partycta.sub':        '10 kits complets dans une boîte à CHF 4,50 pièce — 35% moins cher qu\'à l\'unité.',
    'partycta.btn.unicorn':'🦄 Party Box Licorne',
    'partycta.btn.dino':   '🦕 Party Box Dinosaure',
  },

  de: {
    'meta.title':       "Emma's Lab | Mal-Sets für Kinder Schweiz – Spielzeug, Kreativität & Kindergeburtstag",
    'meta.description': 'Handgemachte Gips-Mal-Sets für Kinder in der Schweiz. Einhorn & Dinosaurier — pädagogisches Spielzeug, kreatives Geschenk oder Beschäftigung für den Kindergeburtstag. Mit Farben, Pinsel & Anleitung. Ab CHF 7.',
    'meta.keywords':    'Malset Kinder Schweiz, Gipsfigur bemalen, pädagogisches Spielzeug Schweiz, kreatives Geschenk Kinder, Kindergeburtstag Aktivität, Bastelset Kinder, Einhorn Spielzeug, Dinosaurier Spielzeug, Beschäftigung Kinder, Handarbeit Kinder Schweiz',
    'nav.about':    'Über uns',
    'nav.contact':  'Kontakt',
    'nav.blog':     'Blog',
    'cart.label':   'Warenkorb',
    'cart.title':   'Warenkorb',
    'cart.empty':   'Ihr Warenkorb ist leer.',
    'cart.subtotal':'Zwischensumme',
    'shop.title':   'Shop',
    'cat.all':      'Alle',
    'cat.unicorn':  'Einhorn',
    'cat.dinosaur': 'Dinosaurier',
    'cat.candle':   'Kerze',
    'about.title':  'Die Künstlerin',
    'about.p1':     'Hallo, ich bin Ekaterina — und Kreativität ist schon immer ein Teil meines Lebens gewesen. Ich besuchte eine Kunstschule und lernte dabei, Schönheit in Farben, Details und den kleinen Dingen zu sehen, die die meisten Menschen übersehen. Seitdem ist das Arbeiten mit meinen Händen mehr als ein Hobby — es ist meine Art, mich auszudrücken.',
    'about.p2':     'Im Laufe der Jahre habe ich viele Formen der Kreativität entdeckt: das Entwerfen handgemachter Teppiche, das Stricken von Pullovern Masche für Masche, das Herstellen von Kerzen und die ständige Freude daran, einfache Materialien in etwas Bedeutungsvolles zu verwandeln.',
    'about.p3':     'Irgendwann entdeckte ich meine Leidenschaft für künstlerisches Make-up und Spezialeffekte — eine weitere Kunstform, um zu kreieren, zu verwandeln und Geschichten zu erzählen. 2019 wurde ich geehrt, von NYX Professional Makeup unter den Top 30 Make-up-Künstlern meines Landes anerkannt zu werden.',
    'about.p4':     'Egal was ich erschaffe — Malerei, Textilien, Kerzen oder Handwerk — das Gefühl ist immer dasselbe: Ich liebe es, gewöhnliche Momente besonders zu machen.',
    'about.p5':     'Dieser Shop wurde aus diesem Gefühl geboren. Ich wollte mehr als nur Malsets schaffen — kleine Momente des Komforts, der Kreativität und der Ruhe. Etwas, das Menschen hilft, innezuhalten, den Prozess zu genießen und mit eigenen Händen etwas Schönes zu erschaffen.',
    'about.p6':     'Ob Sie einen ruhigen Abend allein verbringen, ein durchdachtes Geschenk suchen oder einfach etwas Neues ausprobieren möchten — meine Hoffnung ist, dass diese Kits Wärme, Freude und Kreativität in Ihr Leben bringen.',
    'contact.title':'Kontakt',
    'contact.text': 'Fragen, individuelle Bestellungen, Großhandelsanfragen:',
    'contact.label.email': 'E-Mail',
    'contact.label.phone': 'Telefon',
    'contact.form.title':   'Nachricht senden',
    'contact.form.name':    'Name *',
    'contact.form.email':   'E-Mail *',
    'contact.form.message': 'Nachricht *',
    'contact.form.submit':  'Nachricht senden',
    'contact.form.sending': 'Wird gesendet…',
    'contact.form.success': '✓ Nachricht gesendet! Wir melden uns in Kürze.',
    'contact.form.error':   '✕ Etwas ist schiefgelaufen. Bitte erneut versuchen oder direkt schreiben.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'Alle Rechte vorbehalten.',
    'form.title':   'Anfrage senden',
    'form.name':    'Name *',
    'form.email':   'E-Mail *',
    'form.phone':   'Telefon',
    'form.city':    'Stadt / Postleitzahl',
    'form.address': 'Lieferadresse',
    'form.notes':   'Anmerkungen / Sonderwünsche',
    'form.submit':  'Anfrage senden',
    'form.sending': 'Wird gesendet…',
    'form.success': '✓ Ihre Anfrage wurde gesendet! Wir werden Sie in Kürze kontaktieren.',
    'form.error':   '✕ Etwas ist schiefgelaufen. Bitte versuche es erneut oder kontaktiere uns direkt.',
    'add.to.cart':  'In den Warenkorb',
    'badge.sale':   'Angebot',
    'added.toast':  'In den Warenkorb gelegt',
    'shipping.ch':   'Versand innerhalb der Schweiz: CHF 8',
    'shipping.intl': 'Internationaler Versand: Preis wird per E-Mail bestätigt',
    'hero.eyebrow':  'Handgemacht in der Schweiz',
    'hero.headline': 'Bemale dein eigenes Einhorn oder deinen Dinosaurier',
    'hero.sub':      'Handgemachte Gipsmalerei-Sets mit allem dabei — einfach öffnen, malen und genießen. Perfekt für Geburtstage, Familienabende und kreative Geschenke.',
    'hero.cta':      'Alle Sets ansehen',
    'pain.intro':    'Klingt bekannt?',
    'pain.1':        'Suchst du eine Geburtstagsaktivität, die die ganze Gruppe wirklich begeistert — nicht nur zuschaut?',
    'pain.2':        'Brauchst du ein kreatives Geschenk, das sich von gewöhnlichem Spielzeug abhebt und wirklich genutzt wird?',
    'pain.3':        'Möchtest du gemeinsam Zeit verbringen und etwas mit eigenen Händen erschaffen — ohne Bildschirme?',
    'benefit.title':    'Alles dabei, direkt in der Box',
    'benefit.1.title':  'Alles inklusive',
    'benefit.1.text':   'Figur, Farben, Pinsel, Postkarte & Sticker — nichts wird extra benötigt',
    'benefit.2.title':  'Aufmachen & Malen',
    'benefit.2.text':   'In Sekunden bereit. Keine Vorbereitung, keine Erfahrung nötig',
    'benefit.3.title':  'Handgemacht in der Schweiz',
    'benefit.3.text':   'Jede Gipsfigur wird sorgfältig und mit Liebe zum Detail gegossen',
    'benefit.4.title':  'Auch für Gruppen',
    'benefit.4.text':   'Party Box mit 10 kompletten Sets — perfekt für Geburtstage und Events',
    'partycta.tag':        'Bestes Angebot',
    'partycta.title':      'Eine Party in Planung?',
    'partycta.sub':        '10 komplette Sets in einer Box für je CHF 4,50 — 35% günstiger als Einzelkauf.',
    'partycta.btn.unicorn':'🦄 Einhorn Party Box',
    'partycta.btn.dino':   '🦕 Dinosaurier Party Box',
  },

  ru: {
    'meta.title':       "Emma's Lab | Наборы для рисования для детей в Швейцарии – Игрушки, творчество и праздники",
    'meta.description': 'Наборы для раскрашивания гипсовых фигурок ручной работы для детей в Швейцарии. Единороги и динозавры — развивающая игрушка, творческий подарок или активность на день рождения. Краски, кисть и инструкция в комплекте. От CHF 7. Заказ онлайн.',
    'meta.keywords':    'набор для рисования дети Швейцария, гипсовая фигурка раскрасить, развивающая игрушка Швейцария, творческий подарок ребёнку, активность на день рождения дети, поделки для детей, игрушка единорог, игрушка динозавр, детский праздник активность, хэндмейд Швейцария',
    'nav.about':    'О нас',
    'nav.contact':  'Контакт',
    'nav.blog':     'Блог',
    'cart.label':   'Корзина',
    'cart.title':   'Корзина',
    'cart.empty':   'Ваша корзина пуста.',
    'cart.subtotal':'Итого',
    'shop.title':   'Магазин',
    'cat.all':      'Все',
    'cat.unicorn':  'Единорог',
    'cat.dinosaur': 'Динозавр',
    'cat.candle':   'Свечи',
    'about.title':  'О создателе',
    'about.p1':     'Привет, я Екатерина — и творчество было частью моей жизни, сколько я себя помню. Я училась в художественной школе, где научилась видеть красоту в цветах, деталях и мелочах, которые большинство людей не замечают. С тех пор работа руками стала для меня чем-то большим, чем хобби — это мой способ выражать себя.',
    'about.p2':     'За эти годы я открыла для себя множество форм творчества: дизайн ковров ручной работы, вязание свитеров стежок за стежком, изготовление свечей и постоянную радость превращения простых материалов во что-то значимое.',
    'about.p3':     'В какой-то момент я увлеклась художественным макияжем и спецэффектами — ещё одной формой искусства, чтобы создавать, преображать и рассказывать истории. В 2019 году меня удостоили чести войти в топ-30 визажистов страны по версии NYX Professional Makeup.',
    'about.p4':     'Что бы я ни создавала — живопись, текстиль, свечи или изделия ручной работы — ощущение всегда одно: я люблю делать обычные моменты особенными.',
    'about.p5':     'Этот магазин родился из этого чувства. Я хотела создать не просто наборы для рисования — маленькие моменты уюта, творчества и спокойствия. Что-то, что помогает людям замедлиться, насладиться процессом и сделать что-то красивое своими руками.',
    'about.p6':     'Проводите ли вы тихий вечер в одиночестве, ищете ли вдумчивый подарок или просто хотите попробовать что-то новое — надеюсь, эти наборы принесут в вашу жизнь тепло, радость и вдохновение.',
    'contact.title':'Связаться с нами',
    'contact.text': 'Вопросы, индивидуальные заказы, оптовые запросы:',
    'contact.label.email': 'Эл. почта',
    'contact.label.phone': 'Телефон',
    'contact.form.title':   'Отправить сообщение',
    'contact.form.name':    'Имя *',
    'contact.form.email':   'Эл. почта *',
    'contact.form.message': 'Сообщение *',
    'contact.form.submit':  'Отправить',
    'contact.form.sending': 'Отправка…',
    'contact.form.success': '✓ Сообщение отправлено! Мы свяжемся с вами в ближайшее время.',
    'contact.form.error':   '✕ Что-то пошло не так. Попробуйте ещё раз или напишите нам напрямую.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'Все права защищены.',
    'form.title':   'Отправить заявку',
    'form.name':    'Имя *',
    'form.email':   'Эл. почта *',
    'form.phone':   'Телефон',
    'form.city':    'Город / Почтовый индекс',
    'form.address': 'Адрес доставки',
    'form.notes':   'Примечания / Особые пожелания',
    'form.submit':  'Отправить заявку',
    'form.sending': 'Отправка…',
    'form.success': '✓ Ваша заявка отправлена! Мы свяжемся с вами в ближайшее время.',
    'form.error':   '✕ Что-то пошло не так. Попробуйте ещё раз или свяжитесь с нами напрямую.',
    'add.to.cart':  'В корзину',
    'badge.sale':   'Скидка',
    'added.toast':  'Добавлено в корзину',
    'shipping.ch':   'Доставка по Швейцарии: CHF 8',
    'shipping.intl': 'Международная доставка: стоимость сообщим в ответном письме',
    'hero.eyebrow':  'Ручная работа в Швейцарии',
    'hero.headline': 'Раскрась своего единорога или динозавра',
    'hero.sub':      'Наборы для росписи гипсовых фигурок ручной работы — всё включено. Откройте коробку, рисуйте и наслаждайтесь. Идеально для дней рождений, семейных вечеров и творческих подарков.',
    'hero.cta':      'Смотреть наборы',
    'pain.intro':    'Узнаёте себя?',
    'pain.1':        'Ищете активность на день рождения, от которой весь класс будет в восторге — а не просто смотреть?',
    'pain.2':        'Нужен творческий подарок, который выделяется среди обычных игрушек и которым реально пользуются?',
    'pain.3':        'Хотите провести время вместе и сделать что-то своими руками — без телефонов и экранов?',
    'benefit.title':    'Всё необходимое уже в коробке',
    'benefit.1.title':  'Всё включено',
    'benefit.1.text':   'Фигурка, краски, кисть, открытка и наклейки — ничего докупать не нужно',
    'benefit.2.title':  'Открыть и рисовать',
    'benefit.2.text':   'Готово за секунды. Никакой подготовки, никакого опыта не требуется',
    'benefit.3.title':  'Ручная работа в Швейцарии',
    'benefit.3.text':   'Каждая гипсовая фигурка отлита вручную с вниманием к деталям',
    'benefit.4.title':  'Подходит для группы',
    'benefit.4.text':   'Party Box — 10 полных наборов для дней рождений и мероприятий',
    'partycta.tag':        'Лучшая цена',
    'partycta.title':      'Планируете вечеринку?',
    'partycta.sub':        '10 полных наборов в одной коробке по CHF 4.50 за штуку — на 35% дешевле, чем по одному.',
    'partycta.btn.unicorn':'🦄 Party Box с единорогами',
    'partycta.btn.dino':   '🦕 Party Box с динозаврами',
  },
};
