// ═══════════════════════════════════════════════════════════════════════
//  SITE CONFIGURATION  —  edit this file to configure the shop
// ═══════════════════════════════════════════════════════════════════════

const CONFIG = {
  siteName:     "Emma's Lab",
  siteUrl:      'https://emmas-lab.ch', // ← YOUR DOMAIN (no trailing slash)
  contactEmail: 'emmaslabcandle@gmail.com',
  phone:        '+41 78 256 29 52',
  whatsapp:     '41782562952',
  instagram:    'emmas_lab_candle',
  currency:     'CHF',

  // ── EmailJS ─────────────────────────────────────────────────────────
  // Sign up at https://www.emailjs.com, then fill in these three values.
  // Step-by-step instructions are in the README below the CONFIG block.
  emailjs: {
    publicKey:  'fA4Qdc27FVtcfBfhL',
    serviceId:  'service_dfx69bu',
    templateId: 'template_7z11sev',
  },

  // SEO — used in <title>, meta description, og:image etc.
  seo: {
    defaultLang: 'en',
    ogImage: 'https://emmas-lab.ch/images/site/og-cover.webp',
  },

  // ── Candle scents ────────────────────────────────────────────────────
  // Displayed as selectable chips in the product modal for candle items.
  // Add or remove scents here — they appear automatically.
  candleScents: [
    { id: 'vanilla-amber',    en: 'Vanilla & Amber',    fr: 'Vanille & Ambre',     de: 'Vanille & Amber',    ru: 'Ваниль и амбра'    },
    { id: 'lavender-cedar',   en: 'Lavender & Cedar',   fr: 'Lavande & Cèdre',     de: 'Lavendel & Zeder',   ru: 'Лаванда и кедр'    },
    { id: 'cinnamon-orange',  en: 'Cinnamon & Orange',  fr: 'Cannelle & Orange',   de: 'Zimt & Orange',      ru: 'Корица и апельсин' },
    { id: 'rose-sandalwood',  en: 'Rose & Sandalwood',  fr: 'Rose & Santal',       de: 'Rose & Sandelholz',  ru: 'Роза и сандал'     },
    { id: 'eucalyptus-mint',  en: 'Eucalyptus & Mint',  fr: 'Eucalyptus & Menthe', de: 'Eukalyptus & Minze', ru: 'Эвкалипт и мята'   },
    { id: 'unscented',        en: 'Unscented',           fr: 'Sans parfum',         de: 'Ohne Duft',          ru: 'Без аромата'       },
  ],
};

// ═══════════════════════════════════════════════════════════════════════
//  UI TRANSLATIONS  —  strings used in buttons, labels, nav, etc.
//  To add a language: copy one block, change the key, translate strings.
// ═══════════════════════════════════════════════════════════════════════

const TRANSLATIONS = {
  en: {
    'meta.title':       "Emma's Lab | Painting Kits for Kids Switzerland – Toys, Crafts & Party Activities",
    'meta.description': 'Handmade plaster painting kits for kids in Switzerland. Unicorn & dinosaur sets — perfect educational toy, creative gift, or party activity. Includes paints, brush & instructions. From CHF 7. Order online.',
    'meta.keywords':    'painting kit kids Switzerland, plaster figure painting, educational toy Switzerland, creative gift children, party activity kids, craft for kids, unicorn toy, dinosaur toy, kids birthday activity, handmade toy Switzerland',
    'nav.shop':     'Shop',
    'nav.about':    'About',
    'nav.contact':  'Contact',
    'nav.blog':     'Blog',
    'cart.label':   'Cart',
    'cart.title':   'Cart',
    'cart.empty':   'Your cart is empty.',
    'cart.subtotal':'Subtotal',
    'shop.title':   'Shop',
    'scent.label':    'Choose Your Scent',
    'scent.note':     'Each candle is handcrafted with a unique signature scent.',
    'scent.required': 'Please select a scent to continue.',
    'sort.label':      'Sort',
    'sort.default':    'Featured',
    'sort.price-asc':  'Price: Low to High',
    'sort.price-desc': 'Price: High to Low',
    'sort.name-asc':   'Name: A–Z',
    'sort.name-desc':  'Name: Z–A',
    'cat.all':      'All',
    'cat.kids':     'Activity Kits',
    'cat.candle':   'Candle',
    'about.title':  'Meet the Creator',
    'about.p1':     'Hi, I\'m Ekaterina — and creating has been part of my life for as long as I can remember. I studied at art school while growing up, where I learned to see beauty in colors, details, and the little things most people overlook. Since then, making things with my hands became more than a hobby — it became the way I express myself.',
    'about.p2':     'Over the years, I\'ve explored many kinds of creativity: designing handmade rugs, knitting sweaters stitch by stitch, making candles by hand, and constantly finding joy in turning simple materials into something meaningful.',
    'about.p3':     'At one point, I became deeply passionate about artistic makeup and special effects — another form of art to create, transform, and tell stories. In 2019, I was honored to be recognized among the Top 30 makeup artists in my country by NYX Professional Makeup.',
    'about.p4':     'No matter what I create — paint, textiles, candles, or handmade crafts — the feeling is always the same: I love making ordinary moments feel special.',
    'about.p5':     'This shop was born from that feeling. I wanted to create more than just painting kits — small moments of comfort, creativity, and calm. Something that helps people slow down, enjoy the process, and make something beautiful with their own hands.',
    'about.p6':     'Whether you\'re spending a quiet evening alone, looking for a thoughtful gift, or simply wanting to try something new — my hope is that these kits bring warmth, joy, and creativity into your life.',
    'contact.title':'Get in touch',
    'contact.text': 'Questions, custom orders, wholesale inquiries:',
    'contact.label.email': 'Email',
    'contact.label.phone': 'Phone',
    'contact.form.title':   'Send a Message',
    'contact.form.name':    'Name *',
    'contact.form.email':   'Email *',
    'contact.form.message': 'Message *',
    'contact.form.submit':  'Send Message',
    'contact.form.sending': 'Sending…',
    'contact.form.success': '✓ Message sent! We\'ll get back to you shortly.',
    'contact.form.error':   '✕ Something went wrong. Please try again or email us directly.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'All rights reserved.',
    'form.title':   'Send a Request',
    'form.name':    'Name *',
    'form.email':   'Email *',
    'form.phone':   'Phone',
    'form.city':    'City / Postcode',
    'form.address': 'Delivery Address',
    'form.notes':   'Notes / Special requests',
    'form.submit':  'Send Request',
    'form.sending': 'Sending…',
    'form.success': '✓ Your request has been sent! We will contact you shortly.',
    'form.error':   '✕ Something went wrong. Please try again or contact us directly.',
    'product.size': 'Size',
    'add.to.cart':  'Add to Cart',
    'badge.sale':   'Sale',
    'added.toast':  'Added to cart',
    'shipping.ch':   'Shipping within Switzerland: CHF 8',
    'shipping.intl': 'International shipping: rate confirmed in your reply email',
    'hero.eyebrow':  'Handmade in Switzerland',
    'hero.headline': 'Handmade Crafts & Candles from Switzerland',
    'hero.sub':      'Plaster painting kits and sculptural candles — handcrafted with care. Perfect for birthdays, gifts, and creative moments at home.',
    'hero.cta':      'Shop Now',
    'pain.intro':    'Sound familiar?',
    'pain.1':        'Looking for a birthday activity the whole group will actually enjoy — not just watch?',
    'pain.2':        'Need a creative gift that stands out from the usual toys and actually gets used?',
    'pain.3':        'Want to spend quality time together and make something with your own hands — without screens?',
    'benefit.title':    'Why Emma\'s Lab Candles',
    'benefit.1.title':  'Handpoured in Switzerland',
    'benefit.1.text':   'Every candle is made by hand in Mettmenstetten — not mass-produced',
    'benefit.2.title':  'Sculptural Art Pieces',
    'benefit.2.text':   'Unique figures that look beautiful lit or unlit — art and candle in one',
    'benefit.3.title':  'Meaningful Gift',
    'benefit.3.text':   'One-of-a-kind pieces that stand apart from anything found in a store',
    'benefit.4.title':  'Make Your Own',
    'benefit.4.text':   'Candle-making kits included — pour, shape, and create your own at home',
    'partycta.tag':        '31 October is Coming',
    'partycta.title':      'The Pumpkin Candle',
    'partycta.sub':        'Halloween is almost here. Our enchanted pumpkin cottage glows from within — hand-sculpted in Switzerland, limited seasonal piece. Order yours before it\'s gone.',
    'partycta.btn.primary':'Shop Pumpkin Candle',
    'partycta.btn.secondary': 'All Candles',
    'b2b.eyebrow':       'For Business',
    'b2b.title':         'Orders for Companies & Events',
    'b2b.card1.title':   'Corporate Gifts',
    'b2b.card1.text':    'Custom sculptural candles with your branding. Unique year-end gifts, client appreciation, or event souvenirs — each handpoured in Switzerland.',
    'b2b.card2.title':   'Workshop Kits',
    'b2b.card2.text':    'Creative team-building evenings: we supply complete candle-making kits for groups. Hands-on, memorable, no experience needed.',
    'b2b.card3.title':   'Wholesale & Bulk',
    'b2b.card3.text':    'Special pricing from 10 pieces. Perfect for boutiques, concept stores, and event planners. Let\'s talk quantities.',
    'b2b.cta':           'Get in Touch',
  },

  fr: {
    'meta.title':       "Emma's Lab | Kits de Peinture pour Enfants Suisse – Jouets, Créativité & Activités Fête",
    'meta.description': 'Kits de peinture en plâtre faits main pour enfants en Suisse. Licornes & dinosaures — jouet éducatif, cadeau créatif ou activité de fête. Avec peintures, pinceau et instructions. Dès CHF 7.',
    'meta.keywords':    'kit peinture enfants Suisse, figurine plâtre à peindre, jouet éducatif Suisse, cadeau créatif enfant, activité anniversaire enfants, loisirs créatifs, jouet licorne, jouet dinosaure, idée cadeau enfant, artisanat enfant Suisse',
    'nav.shop':     'Boutique',
    'nav.about':    'À propos',
    'nav.contact':  'Contact',
    'nav.blog':     'Blog',
    'cart.label':   'Panier',
    'cart.title':   'Panier',
    'cart.empty':   'Votre panier est vide.',
    'cart.subtotal':'Sous-total',
    'shop.title':   'Boutique',
    'scent.label':    'Choisissez votre parfum',
    'scent.note':     'Chaque bougie est fabriquée à la main avec un parfum signature unique.',
    'scent.required': 'Veuillez sélectionner un parfum pour continuer.',
    'sort.label':      'Trier',
    'sort.default':    'Par défaut',
    'sort.price-asc':  'Prix: croissant',
    'sort.price-desc': 'Prix: décroissant',
    'sort.name-asc':   'Nom: A–Z',
    'sort.name-desc':  'Nom: Z–A',
    'cat.all':      'Tout',
    'cat.kids':     'Kits Créatifs',
    'cat.candle':   'Bougie',
    'about.title':  'Rencontrez la Créatrice',
    'about.p1':     "Bonjour, je suis Ekaterina — et la création fait partie de ma vie depuis toujours. J'ai étudié aux beaux-arts dans ma jeunesse, où j'ai appris à voir la beauté dans les couleurs, les détails et les petites choses que la plupart des gens ne remarquent pas. Depuis, créer avec mes mains est devenu bien plus qu'un passe-temps — c'est ma façon de m'exprimer.",
    'about.p2':     "Au fil des années, j'ai exploré de nombreuses formes de créativité : la conception de tapis faits main, le tricot de pulls point par point, la fabrication de bougies artisanales, et la joie constante de transformer des matériaux simples en quelque chose de beau.",
    'about.p3':     "À un moment, je me suis passionnée pour le maquillage artistique et les effets spéciaux — une autre forme d'art pour créer, transformer et raconter des histoires. En 2019, j'ai eu l'honneur d'être reconnue parmi les 30 meilleurs maquilleurs de mon pays par NYX Professional Makeup.",
    'about.p4':     "Peu importe ce que je crée — peinture, textiles, bougies ou artisanat — le sentiment est toujours le même : j'aime rendre les moments ordinaires extraordinaires.",
    'about.p5':     "Cette boutique est née de ce sentiment. Je voulais créer plus que de simples kits de peinture — de petits moments de confort, de créativité et de calme. Quelque chose qui aide les gens à ralentir, à apprécier le processus et à créer quelque chose de beau de leurs propres mains.",
    'about.p6':     "Que vous passiez une soirée tranquille seul, que vous cherchiez un cadeau attentionné, ou que vous souhaitiez simplement essayer quelque chose de nouveau — mon espoir est que ces kits apportent chaleur, joie et créativité dans votre vie.",
    'contact.title':'Contactez-nous',
    'contact.text': 'Questions, commandes personnalisées, ventes en gros :',
    'contact.label.email': 'E-mail',
    'contact.label.phone': 'Téléphone',
    'contact.form.title':   'Envoyer un message',
    'contact.form.name':    'Nom *',
    'contact.form.email':   'E-mail *',
    'contact.form.message': 'Message *',
    'contact.form.submit':  'Envoyer le message',
    'contact.form.sending': 'Envoi…',
    'contact.form.success': '✓ Message envoyé ! Nous vous répondrons sous peu.',
    'contact.form.error':   '✕ Une erreur est survenue. Réessayez ou écrivez-nous directement.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'Tous droits réservés.',
    'form.title':   'Envoyer une demande',
    'form.name':    'Nom *',
    'form.email':   'E-mail *',
    'form.phone':   'Téléphone',
    'form.city':    'Ville / Code postal',
    'form.address': 'Adresse de livraison',
    'form.notes':   'Notes / Demandes spéciales',
    'form.submit':  'Envoyer la demande',
    'form.sending': 'Envoi en cours…',
    'form.success': '✓ Votre demande a été envoyée ! Nous vous contacterons prochainement.',
    'form.error':   '✕ Une erreur est survenue. Veuillez réessayer ou nous contacter directement.',
    'product.size': 'Taille',
    'add.to.cart':  'Ajouter au panier',
    'badge.sale':   'Solde',
    'added.toast':  'Ajouté au panier',
    'shipping.ch':   'Livraison en Suisse : CHF 8',
    'shipping.intl': 'Livraison internationale : tarif confirmé dans votre e-mail de réponse',
    'hero.eyebrow':  'Fait main en Suisse',
    'hero.headline': 'Créations artisanales & bougies de Suisse',
    'hero.sub':      'Kits de peinture en plâtre et bougies sculptées — faits à la main avec soin. Parfaits pour les anniversaires, les cadeaux et les moments créatifs.',
    'hero.cta':      'Découvrir',
    'pain.intro':    'Vous vous reconnaissez ?',
    'pain.1':        'Vous cherchez une activité d\'anniversaire que tout le groupe adorera — pas juste regarder ?',
    'pain.2':        'Vous avez besoin d\'un cadeau créatif qui se démarque des jouets habituels et qui sera vraiment utilisé ?',
    'pain.3':        'Vous voulez passer du temps de qualité ensemble et créer quelque chose de vos propres mains — sans écrans ?',
    'benefit.title':    'Pourquoi Emma\'s Lab',
    'benefit.1.title':  'Coulées à la main en Suisse',
    'benefit.1.text':   'Chaque bougie est fabriquée à la main à Mettmenstetten — pas de production en série',
    'benefit.2.title':  'Pièces d\'art sculpturales',
    'benefit.2.text':   'Des figures uniques, belles allumées ou non — art et bougie réunis',
    'benefit.3.title':  'Cadeau unique',
    'benefit.3.text':   'Des créations uniques introuvables en boutique',
    'benefit.4.title':  'Faites la vôtre',
    'benefit.4.text':   'Kits de fabrication de bougies inclus — coulez, façonnez et créez chez vous',
    'partycta.tag':        'Le 31 octobre approche',
    'partycta.title':      'La Bougie Citrouille',
    'partycta.sub':        'Halloween arrive bientôt. Notre cottage citrouille enchanté rayonne de l\'intérieur — sculpté à la main en Suisse, pièce saisonnière limitée. Commandez avant qu\'il ne soit trop tard.',
    'partycta.btn.primary':'Acheter la bougie citrouille',
    'partycta.btn.secondary': 'Toutes les bougies',
    'b2b.eyebrow':       'Pour les entreprises',
    'b2b.title':         'Commandes professionnelles & événements',
    'b2b.card1.title':   'Cadeaux d\'entreprise',
    'b2b.card1.text':    'Bougies sculpturales personnalisées à votre image. Idéales pour les fêtes de fin d\'année, cadeaux clients ou souvenirs d\'événements — coulées à la main en Suisse.',
    'b2b.card2.title':   'Ateliers DIY',
    'b2b.card2.text':    'Team building créatif : nous fournissons des kits complets de fabrication de bougies pour vos groupes. Ludique, mémorable, sans expérience requise.',
    'b2b.card3.title':   'Vente en gros',
    'b2b.card3.text':    'Tarifs préférentiels dès 10 pièces. Idéal pour boutiques, concept stores et organisateurs d\'événements.',
    'b2b.cta':           'Nous contacter',
  },

  de: {
    'meta.title':       "Emma's Lab | Mal-Sets für Kinder Schweiz – Spielzeug, Kreativität & Kindergeburtstag",
    'meta.description': 'Handgemachte Gips-Mal-Sets für Kinder in der Schweiz. Einhorn & Dinosaurier — pädagogisches Spielzeug, kreatives Geschenk oder Beschäftigung für den Kindergeburtstag. Mit Farben, Pinsel & Anleitung. Ab CHF 7.',
    'meta.keywords':    'Malset Kinder Schweiz, Gipsfigur bemalen, pädagogisches Spielzeug Schweiz, kreatives Geschenk Kinder, Kindergeburtstag Aktivität, Bastelset Kinder, Einhorn Spielzeug, Dinosaurier Spielzeug, Beschäftigung Kinder, Handarbeit Kinder Schweiz',
    'nav.shop':     'Shop',
    'nav.about':    'Über uns',
    'nav.contact':  'Kontakt',
    'nav.blog':     'Blog',
    'cart.label':   'Warenkorb',
    'cart.title':   'Warenkorb',
    'cart.empty':   'Ihr Warenkorb ist leer.',
    'cart.subtotal':'Zwischensumme',
    'shop.title':   'Shop',
    'scent.label':    'Wähle deinen Duft',
    'scent.note':     'Jede Kerze wird mit einem einzigartigen Signaturduft handgefertigt.',
    'scent.required': 'Bitte wähle einen Duft aus, um fortzufahren.',
    'sort.label':      'Sortieren',
    'sort.default':    'Standard',
    'sort.price-asc':  'Preis: aufsteigend',
    'sort.price-desc': 'Preis: absteigend',
    'sort.name-asc':   'Name: A–Z',
    'sort.name-desc':  'Name: Z–A',
    'cat.all':      'Alle',
    'cat.kids':     'Kreativ-Sets',
    'cat.candle':   'Kerze',
    'about.title':  'Die Künstlerin',
    'about.p1':     'Hallo, ich bin Ekaterina — und Kreativität ist schon immer ein Teil meines Lebens gewesen. Ich besuchte eine Kunstschule und lernte dabei, Schönheit in Farben, Details und den kleinen Dingen zu sehen, die die meisten Menschen übersehen. Seitdem ist das Arbeiten mit meinen Händen mehr als ein Hobby — es ist meine Art, mich auszudrücken.',
    'about.p2':     'Im Laufe der Jahre habe ich viele Formen der Kreativität entdeckt: das Entwerfen handgemachter Teppiche, das Stricken von Pullovern Masche für Masche, das Herstellen von Kerzen und die ständige Freude daran, einfache Materialien in etwas Bedeutungsvolles zu verwandeln.',
    'about.p3':     'Irgendwann entdeckte ich meine Leidenschaft für künstlerisches Make-up und Spezialeffekte — eine weitere Kunstform, um zu kreieren, zu verwandeln und Geschichten zu erzählen. 2019 wurde ich geehrt, von NYX Professional Makeup unter den Top 30 Make-up-Künstlern meines Landes anerkannt zu werden.',
    'about.p4':     'Egal was ich erschaffe — Malerei, Textilien, Kerzen oder Handwerk — das Gefühl ist immer dasselbe: Ich liebe es, gewöhnliche Momente besonders zu machen.',
    'about.p5':     'Dieser Shop wurde aus diesem Gefühl geboren. Ich wollte mehr als nur Malsets schaffen — kleine Momente des Komforts, der Kreativität und der Ruhe. Etwas, das Menschen hilft, innezuhalten, den Prozess zu genießen und mit eigenen Händen etwas Schönes zu erschaffen.',
    'about.p6':     'Ob Sie einen ruhigen Abend allein verbringen, ein durchdachtes Geschenk suchen oder einfach etwas Neues ausprobieren möchten — meine Hoffnung ist, dass diese Kits Wärme, Freude und Kreativität in Ihr Leben bringen.',
    'contact.title':'Kontakt',
    'contact.text': 'Fragen, individuelle Bestellungen, Großhandelsanfragen:',
    'contact.label.email': 'E-Mail',
    'contact.label.phone': 'Telefon',
    'contact.form.title':   'Nachricht senden',
    'contact.form.name':    'Name *',
    'contact.form.email':   'E-Mail *',
    'contact.form.message': 'Nachricht *',
    'contact.form.submit':  'Nachricht senden',
    'contact.form.sending': 'Wird gesendet…',
    'contact.form.success': '✓ Nachricht gesendet! Wir melden uns in Kürze.',
    'contact.form.error':   '✕ Etwas ist schiefgelaufen. Bitte erneut versuchen oder direkt schreiben.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'Alle Rechte vorbehalten.',
    'form.title':   'Anfrage senden',
    'form.name':    'Name *',
    'form.email':   'E-Mail *',
    'form.phone':   'Telefon',
    'form.city':    'Stadt / Postleitzahl',
    'form.address': 'Lieferadresse',
    'form.notes':   'Anmerkungen / Sonderwünsche',
    'form.submit':  'Anfrage senden',
    'form.sending': 'Wird gesendet…',
    'form.success': '✓ Ihre Anfrage wurde gesendet! Wir werden Sie in Kürze kontaktieren.',
    'form.error':   '✕ Etwas ist schiefgelaufen. Bitte versuche es erneut oder kontaktiere uns direkt.',
    'product.size': 'Größe',
    'add.to.cart':  'In den Warenkorb',
    'badge.sale':   'Angebot',
    'added.toast':  'In den Warenkorb gelegt',
    'shipping.ch':   'Versand innerhalb der Schweiz: CHF 8',
    'shipping.intl': 'Internationaler Versand: Preis wird per E-Mail bestätigt',
    'hero.eyebrow':  'Handgemacht in der Schweiz',
    'hero.headline': 'Handgemachte Kreationen & Kerzen aus der Schweiz',
    'hero.sub':      'Gipsmalerei-Sets und skulpturale Kerzen — liebevoll von Hand gefertigt. Perfekt für Geburtstage, Geschenke und kreative Momente zu Hause.',
    'hero.cta':      'Jetzt entdecken',
    'pain.intro':    'Klingt bekannt?',
    'pain.1':        'Suchst du eine Geburtstagsaktivität, die die ganze Gruppe wirklich begeistert — nicht nur zuschaut?',
    'pain.2':        'Brauchst du ein kreatives Geschenk, das sich von gewöhnlichem Spielzeug abhebt und wirklich genutzt wird?',
    'pain.3':        'Möchtest du gemeinsam Zeit verbringen und etwas mit eigenen Händen erschaffen — ohne Bildschirme?',
    'benefit.title':    'Warum Emma\'s Lab',
    'benefit.1.title':  'Handgegossen in der Schweiz',
    'benefit.1.text':   'Jede Kerze wird in Mettmenstetten von Hand gefertigt — keine Massenproduktion',
    'benefit.2.title':  'Skulpturale Kunstwerke',
    'benefit.2.text':   'Einzigartige Figuren, die angezündet oder unangezündet wunderschön aussehen',
    'benefit.3.title':  'Bedeutungsvolles Geschenk',
    'benefit.3.text':   'Unikate, die man in keinem Laden findet',
    'benefit.4.title':  'Selber machen',
    'benefit.4.text':   'Kerzengiess-Sets inklusive — formen, giessen und zu Hause kreieren',
    'partycta.tag':        '31. Oktober naht',
    'partycta.title':      'Die Kürbis-Kerze',
    'partycta.sub':        'Halloween steht vor der Tür. Unser verzaubertes Kürbis-Häuschen leuchtet von innen — handgefertigt in der Schweiz, limitiertes Saisonstück. Jetzt bestellen, solange der Vorrat reicht.',
    'partycta.btn.primary':'Kürbis-Kerze kaufen',
    'partycta.btn.secondary': 'Alle Kerzen',
    'b2b.eyebrow':       'Für Unternehmen',
    'b2b.title':         'Bestellungen für Firmen & Events',
    'b2b.card1.title':   'Firmengeschenke',
    'b2b.card1.text':    'Massgeschneiderte Kerzen mit Ihrem Branding. Einzigartige Jahresend-Geschenke, Kundengeschenke oder Event-Souvenirs — handgegossen in der Schweiz.',
    'b2b.card2.title':   'Workshop-Kits',
    'b2b.card2.text':    'Kreatives Teamevent: Wir liefern komplette Kerzengiess-Sets für Gruppen. Hands-on, unvergesslich, ohne Vorkenntnisse.',
    'b2b.card3.title':   'Grosshandel & Mengen',
    'b2b.card3.text':    'Sonderpreise ab 10 Stück. Ideal für Boutiquen, Concept Stores und Event-Planer.',
    'b2b.cta':           'Kontakt aufnehmen',
  },

  ru: {
    'meta.title':       "Emma's Lab | Наборы для рисования для детей в Швейцарии – Игрушки, творчество и праздники",
    'meta.description': 'Наборы для раскрашивания гипсовых фигурок ручной работы для детей в Швейцарии. Единороги и динозавры — развивающая игрушка, творческий подарок или активность на день рождения. Краски, кисть и инструкция в комплекте. От CHF 7. Заказ онлайн.',
    'meta.keywords':    'набор для рисования дети Швейцария, гипсовая фигурка раскрасить, развивающая игрушка Швейцария, творческий подарок ребёнку, активность на день рождения дети, поделки для детей, игрушка единорог, игрушка динозавр, детский праздник активность, хэндмейд Швейцария',
    'nav.shop':     'Магазин',
    'nav.about':    'О нас',
    'nav.contact':  'Контакт',
    'nav.blog':     'Блог',
    'cart.label':   'Корзина',
    'cart.title':   'Корзина',
    'cart.empty':   'Ваша корзина пуста.',
    'cart.subtotal':'Итого',
    'shop.title':   'Магазин',
    'scent.label':    'Выберите аромат',
    'scent.note':     'Каждая свеча создаётся вручную с уникальным авторским ароматом.',
    'scent.required': 'Пожалуйста, выберите аромат чтобы продолжить.',
    'sort.label':      'Сортировка',
    'sort.default':    'По умолчанию',
    'sort.price-asc':  'Цена: по возрастанию',
    'sort.price-desc': 'Цена: по убыванию',
    'sort.name-asc':   'Название: А–Я',
    'sort.name-desc':  'Название: Я–А',
    'cat.all':      'Все',
    'cat.kids':     'Развивашки',
    'cat.candle':   'Свечи',
    'about.title':  'О создателе',
    'about.p1':     'Привет, я Екатерина — и творчество было частью моей жизни, сколько я себя помню. Я училась в художественной школе, где научилась видеть красоту в цветах, деталях и мелочах, которые большинство людей не замечают. С тех пор работа руками стала для меня чем-то большим, чем хобби — это мой способ выражать себя.',
    'about.p2':     'За эти годы я открыла для себя множество форм творчества: дизайн ковров ручной работы, вязание свитеров стежок за стежком, изготовление свечей и постоянную радость превращения простых материалов во что-то значимое.',
    'about.p3':     'В какой-то момент я увлеклась художественным макияжем и спецэффектами — ещё одной формой искусства, чтобы создавать, преображать и рассказывать истории. В 2019 году меня удостоили чести войти в топ-30 визажистов страны по версии NYX Professional Makeup.',
    'about.p4':     'Что бы я ни создавала — живопись, текстиль, свечи или изделия ручной работы — ощущение всегда одно: я люблю делать обычные моменты особенными.',
    'about.p5':     'Этот магазин родился из этого чувства. Я хотела создать не просто наборы для рисования — маленькие моменты уюта, творчества и спокойствия. Что-то, что помогает людям замедлиться, насладиться процессом и сделать что-то красивое своими руками.',
    'about.p6':     'Проводите ли вы тихий вечер в одиночестве, ищете ли вдумчивый подарок или просто хотите попробовать что-то новое — надеюсь, эти наборы принесут в вашу жизнь тепло, радость и вдохновение.',
    'contact.title':'Связаться с нами',
    'contact.text': 'Вопросы, индивидуальные заказы, оптовые запросы:',
    'contact.label.email': 'Эл. почта',
    'contact.label.phone': 'Телефон',
    'contact.form.title':   'Отправить сообщение',
    'contact.form.name':    'Имя *',
    'contact.form.email':   'Эл. почта *',
    'contact.form.message': 'Сообщение *',
    'contact.form.submit':  'Отправить',
    'contact.form.sending': 'Отправка…',
    'contact.form.success': '✓ Сообщение отправлено! Мы свяжемся с вами в ближайшее время.',
    'contact.form.error':   '✕ Что-то пошло не так. Попробуйте ещё раз или напишите нам напрямую.',
    'footer.brand': "Emma's Lab",
    'footer.rights':'Все права защищены.',
    'form.title':   'Отправить заявку',
    'form.name':    'Имя *',
    'form.email':   'Эл. почта *',
    'form.phone':   'Телефон',
    'form.city':    'Город / Почтовый индекс',
    'form.address': 'Адрес доставки',
    'form.notes':   'Примечания / Особые пожелания',
    'form.submit':  'Отправить заявку',
    'form.sending': 'Отправка…',
    'form.success': '✓ Ваша заявка отправлена! Мы свяжемся с вами в ближайшее время.',
    'form.error':   '✕ Что-то пошло не так. Попробуйте ещё раз или свяжитесь с нами напрямую.',
    'product.size': 'Размер',
    'add.to.cart':  'В корзину',
    'badge.sale':   'Скидка',
    'added.toast':  'Добавлено в корзину',
    'shipping.ch':   'Доставка по Швейцарии: CHF 8',
    'shipping.intl': 'Международная доставка: стоимость сообщим в ответном письме',
    'hero.eyebrow':  'Ручная работа в Швейцарии',
    'hero.headline': 'Хэнд­мейд из Швейцарии — наборы и свечи',
    'hero.sub':      'Наборы для росписи гипса и скульптурные свечи ручной работы. Идеально для дней рождений, подарков и творческих вечеров дома.',
    'hero.cta':      'В магазин',
    'pain.intro':    'Узнаёте себя?',
    'pain.1':        'Ищете активность на день рождения, от которой весь класс будет в восторге — а не просто смотреть?',
    'pain.2':        'Нужен творческий подарок, который выделяется среди обычных игрушек и которым реально пользуются?',
    'pain.3':        'Хотите провести время вместе и сделать что-то своими руками — без телефонов и экранов?',
    'benefit.title':    'Почему Emma\'s Lab',
    'benefit.1.title':  'Ручная работа в Швейцарии',
    'benefit.1.text':   'Каждая свеча сделана вручную в Меттменштеттен — никакого массового производства',
    'benefit.2.title':  'Скульптурное искусство',
    'benefit.2.text':   'Уникальные фигуры, красивые как с огнём, так и без — искусство и свеча в одном',
    'benefit.3.title':  'Особенный подарок',
    'benefit.3.text':   'Штучные изделия, которых не найти ни в одном магазине',
    'benefit.4.title':  'Сделай сам',
    'benefit.4.text':   'Наборы для изготовления свечей — создай свою свечу дома',
    'partycta.tag':        'До 31 октября совсем мало',
    'partycta.title':      'Тыквенная свеча',
    'partycta.sub':        'Хэллоуин уже близко. Наш зачарованный тыквенный домик светится изнутри — ручная работа в Швейцарии, лимитированный сезонный экземпляр. Успей заказать до того, как разберут.',
    'partycta.btn.primary':'Купить тыквенную свечу',
    'partycta.btn.secondary': 'Все свечи',
    'b2b.eyebrow':       'Для бизнеса',
    'b2b.title':         'Заказы для компаний и мероприятий',
    'b2b.card1.title':   'Корпоративные подарки',
    'b2b.card1.text':    'Кастомные свечи с брендингом вашей компании. Уникальные подарки на конец года, клиентам или сувениры с мероприятий — ручная работа в Швейцарии.',
    'b2b.card2.title':   'Мастер-классы',
    'b2b.card2.text':    'Творческий тимбилдинг: мы поставляем наборы для изготовления свечей для групп. Увлекательно, незабываемо, без опыта.',
    'b2b.card3.title':   'Оптовые заказы',
    'b2b.card3.text':    'Специальные цены от 10 штук. Идеально для бутиков, концепт-сторов и организаторов мероприятий.',
    'b2b.cta':           'Связаться с нами',
  },
};
