// ═══════════════════════════════════════════════════════════════════════
//  SITE CONFIGURATION  —  edit this file to configure the shop
// ═══════════════════════════════════════════════════════════════════════

const CONFIG = {
  siteName:     "Emma's Creative Learning",
  siteUrl:      'https://emmas-lab.ch', // ← YOUR DOMAIN (no trailing slash)
  contactEmail: 'emmalabcandle@gmail.com',
  phone:        '+41 78 256 29 52',
  whatsapp:     '41782562952',
  instagram:    'emmas_lab_candle',
  currency:     'CHF',

  // ── EmailJS ─────────────────────────────────────────────────────────
  // Sign up at https://www.emailjs.com, then fill in these three values.
  // Step-by-step instructions are in the README below the CONFIG block.
  emailjs: {
    publicKey:  '0pKmMcMTtl03C24h7',
    serviceId:  'service_3l7oy0q',
    templateId: 'template_32nxytd',
  },

  // SEO — used in <title>, meta description, og:image etc.
  seo: {
    defaultLang: 'en',
    ogImage: 'https://emmas-lab.ch/images/og-cover.jpg',
  },
};

// ═══════════════════════════════════════════════════════════════════════
//  UI TRANSLATIONS  —  strings used in buttons, labels, nav, etc.
//  To add a language: copy one block, change the key, translate strings.
// ═══════════════════════════════════════════════════════════════════════

const TRANSLATIONS = {
  en: {
    'meta.title':       "Emma's Lab | Handmade Plaster Painting Kits Switzerland – emmas-lab.ch",
    'meta.description': 'Handmade plaster painting kits for kids and families in Switzerland. Unicorn & dinosaur sets with paints, brush and instructions. Perfect gift. Order online from CHF 7.',
    'nav.about':    'About',
    'nav.contact':  'Contact',
    'cart.label':   'Cart',
    'cart.title':   'Cart',
    'cart.empty':   'Your cart is empty.',
    'cart.subtotal':'Subtotal',
    'shop.title':   'Shop',
    'cat.all':      'All',
    'cat.unicorn':  'Unicorn',
    'cat.dinosaur': 'Dinosaur',
    'about.title':  'Meet the Creator',
    'about.p1':     'Hi, I\'m Ekaterina — and creating has been part of my life for as long as I can remember. I studied at art school while growing up, where I learned to see beauty in colors, details, and the little things most people overlook. Since then, making things with my hands became more than a hobby — it became the way I express myself.',
    'about.p2':     'Over the years, I\'ve explored many kinds of creativity: designing handmade rugs, knitting sweaters stitch by stitch, making candles by hand, and constantly finding joy in turning simple materials into something meaningful.',
    'about.p3':     'At one point, I became deeply passionate about artistic makeup and special effects — another form of art to create, transform, and tell stories. In 2019, I was honored to be recognized among the Top 30 makeup artists in my country by NYX Professional Makeup.',
    'about.p4':     'No matter what I create — paint, textiles, candles, or handmade crafts — the feeling is always the same: I love making ordinary moments feel special.',
    'about.p5':     'This shop was born from that feeling. I wanted to create more than just painting kits — small moments of comfort, creativity, and calm. Something that helps people slow down, enjoy the process, and make something beautiful with their own hands.',
    'about.p6':     'Whether you\'re spending a quiet evening alone, looking for a thoughtful gift, or simply wanting to try something new — my hope is that these kits bring warmth, joy, and creativity into your life.',
    'contact.title':'Get in touch',
    'contact.text': 'Questions, custom orders, wholesale inquiries:',
    'contact.label.email': 'Email',
    'contact.label.phone': 'Phone',
    'contact.form.title':   'Send a Message',
    'contact.form.name':    'Name *',
    'contact.form.email':   'Email *',
    'contact.form.message': 'Message *',
    'contact.form.submit':  'Send Message',
    'contact.form.sending': 'Sending…',
    'contact.form.success': '✓ Message sent! We\'ll get back to you shortly.',
    'contact.form.error':   '✕ Something went wrong. Please try again or email us directly.',
    'footer.brand': "Emma's Creative Learning",
    'footer.rights':'All rights reserved.',
    'form.title':   'Send a Request',
    'form.name':    'Name *',
    'form.email':   'Email *',
    'form.phone':   'Phone',
    'form.city':    'City / Postcode',
    'form.address': 'Delivery Address',
    'form.notes':   'Notes / Special requests',
    'form.submit':  'Send Request',
    'form.sending': 'Sending…',
    'form.success': '✓ Your request has been sent! We will contact you shortly.',
    'form.error':   '✕ Something went wrong. Please try again or contact us directly.',
    'add.to.cart':  'Add to Cart',
    'badge.sale':   'Sale',
    'added.toast':  'Added to cart',
  },

  fr: {
    'meta.title':       "Emma's Lab | Kits de Peinture en Plâtre Suisse – emmas-lab.ch",
    'meta.description': 'Kits de peinture en plâtre faits main pour enfants et familles en Suisse. Licornes et dinosaures avec peintures, pinceau et instructions. Cadeau parfait. Dès CHF 7.',
    'nav.about':    'À propos',
    'nav.contact':  'Contact',
    'cart.label':   'Panier',
    'cart.title':   'Panier',
    'cart.empty':   'Votre panier est vide.',
    'cart.subtotal':'Sous-total',
    'shop.title':   'Boutique',
    'cat.all':      'Tout',
    'cat.unicorn':  'Licorne',
    'cat.dinosaur': 'Dinosaure',
    'about.title':  'Rencontrez la Créatrice',
    'about.p1':     "Bonjour, je suis Ekaterina — et la création fait partie de ma vie depuis toujours. J'ai étudié aux beaux-arts dans ma jeunesse, où j'ai appris à voir la beauté dans les couleurs, les détails et les petites choses que la plupart des gens ne remarquent pas. Depuis, créer avec mes mains est devenu bien plus qu'un passe-temps — c'est ma façon de m'exprimer.",
    'about.p2':     "Au fil des années, j'ai exploré de nombreuses formes de créativité : la conception de tapis faits main, le tricot de pulls point par point, la fabrication de bougies artisanales, et la joie constante de transformer des matériaux simples en quelque chose de beau.",
    'about.p3':     "À un moment, je me suis passionnée pour le maquillage artistique et les effets spéciaux — une autre forme d'art pour créer, transformer et raconter des histoires. En 2019, j'ai eu l'honneur d'être reconnue parmi les 30 meilleurs maquilleurs de mon pays par NYX Professional Makeup.",
    'about.p4':     "Peu importe ce que je crée — peinture, textiles, bougies ou artisanat — le sentiment est toujours le même : j'aime rendre les moments ordinaires extraordinaires.",
    'about.p5':     "Cette boutique est née de ce sentiment. Je voulais créer plus que de simples kits de peinture — de petits moments de confort, de créativité et de calme. Quelque chose qui aide les gens à ralentir, à apprécier le processus et à créer quelque chose de beau de leurs propres mains.",
    'about.p6':     "Que vous passiez une soirée tranquille seul, que vous cherchiez un cadeau attentionné, ou que vous souhaitiez simplement essayer quelque chose de nouveau — mon espoir est que ces kits apportent chaleur, joie et créativité dans votre vie.",
    'contact.title':'Contactez-nous',
    'contact.text': 'Questions, commandes personnalisées, ventes en gros :',
    'contact.label.email': 'E-mail',
    'contact.label.phone': 'Téléphone',
    'contact.form.title':   'Envoyer un message',
    'contact.form.name':    'Nom *',
    'contact.form.email':   'E-mail *',
    'contact.form.message': 'Message *',
    'contact.form.submit':  'Envoyer le message',
    'contact.form.sending': 'Envoi…',
    'contact.form.success': '✓ Message envoyé ! Nous vous répondrons sous peu.',
    'contact.form.error':   '✕ Une erreur est survenue. Réessayez ou écrivez-nous directement.',
    'footer.brand': "Emma's Creative Learning",
    'footer.rights':'Tous droits réservés.',
    'form.title':   'Envoyer une demande',
    'form.name':    'Nom *',
    'form.email':   'E-mail *',
    'form.phone':   'Téléphone',
    'form.city':    'Ville / Code postal',
    'form.address': 'Adresse de livraison',
    'form.notes':   'Notes / Demandes spéciales',
    'form.submit':  'Envoyer la demande',
    'form.sending': 'Envoi en cours…',
    'form.success': '✓ Votre demande a été envoyée ! Nous vous contacterons prochainement.',
    'form.error':   '✕ Une erreur est survenue. Veuillez réessayer ou nous contacter directement.',
    'add.to.cart':  'Ajouter au panier',
    'badge.sale':   'Solde',
    'added.toast':  'Ajouté au panier',
  },

  de: {
    'meta.title':       "Emma's Lab | Handgemachte Gipsmalerei-Sets Schweiz – emmas-lab.ch",
    'meta.description': 'Handgefertigte Gipsmalerei-Kits für Kinder und Familien in der Schweiz. Einhorn- und Dinosaurier-Sets mit Farben, Pinsel und Anleitung. Perfektes Geschenk. Ab CHF 7.',
    'nav.about':    'Über uns',
    'nav.contact':  'Kontakt',
    'cart.label':   'Warenkorb',
    'cart.title':   'Warenkorb',
    'cart.empty':   'Ihr Warenkorb ist leer.',
    'cart.subtotal':'Zwischensumme',
    'shop.title':   'Shop',
    'cat.all':      'Alle',
    'cat.unicorn':  'Einhorn',
    'cat.dinosaur': 'Dinosaurier',
    'about.title':  'Die Künstlerin',
    'about.p1':     'Hallo, ich bin Ekaterina — und Kreativität ist schon immer ein Teil meines Lebens gewesen. Ich besuchte eine Kunstschule und lernte dabei, Schönheit in Farben, Details und den kleinen Dingen zu sehen, die die meisten Menschen übersehen. Seitdem ist das Arbeiten mit meinen Händen mehr als ein Hobby — es ist meine Art, mich auszudrücken.',
    'about.p2':     'Im Laufe der Jahre habe ich viele Formen der Kreativität entdeckt: das Entwerfen handgemachter Teppiche, das Stricken von Pullovern Masche für Masche, das Herstellen von Kerzen und die ständige Freude daran, einfache Materialien in etwas Bedeutungsvolles zu verwandeln.',
    'about.p3':     'Irgendwann entdeckte ich meine Leidenschaft für künstlerisches Make-up und Spezialeffekte — eine weitere Kunstform, um zu kreieren, zu verwandeln und Geschichten zu erzählen. 2019 wurde ich geehrt, von NYX Professional Makeup unter den Top 30 Make-up-Künstlern meines Landes anerkannt zu werden.',
    'about.p4':     'Egal was ich erschaffe — Malerei, Textilien, Kerzen oder Handwerk — das Gefühl ist immer dasselbe: Ich liebe es, gewöhnliche Momente besonders zu machen.',
    'about.p5':     'Dieser Shop wurde aus diesem Gefühl geboren. Ich wollte mehr als nur Malsets schaffen — kleine Momente des Komforts, der Kreativität und der Ruhe. Etwas, das Menschen hilft, innezuhalten, den Prozess zu genießen und mit eigenen Händen etwas Schönes zu erschaffen.',
    'about.p6':     'Ob Sie einen ruhigen Abend allein verbringen, ein durchdachtes Geschenk suchen oder einfach etwas Neues ausprobieren möchten — meine Hoffnung ist, dass diese Kits Wärme, Freude und Kreativität in Ihr Leben bringen.',
    'contact.title':'Kontakt',
    'contact.text': 'Fragen, individuelle Bestellungen, Großhandelsanfragen:',
    'contact.label.email': 'E-Mail',
    'contact.label.phone': 'Telefon',
    'contact.form.title':   'Nachricht senden',
    'contact.form.name':    'Name *',
    'contact.form.email':   'E-Mail *',
    'contact.form.message': 'Nachricht *',
    'contact.form.submit':  'Nachricht senden',
    'contact.form.sending': 'Wird gesendet…',
    'contact.form.success': '✓ Nachricht gesendet! Wir melden uns in Kürze.',
    'contact.form.error':   '✕ Etwas ist schiefgelaufen. Bitte erneut versuchen oder direkt schreiben.',
    'footer.brand': "Emma's Creative Learning",
    'footer.rights':'Alle Rechte vorbehalten.',
    'form.title':   'Anfrage senden',
    'form.name':    'Name *',
    'form.email':   'E-Mail *',
    'form.phone':   'Telefon',
    'form.city':    'Stadt / Postleitzahl',
    'form.address': 'Lieferadresse',
    'form.notes':   'Anmerkungen / Sonderwünsche',
    'form.submit':  'Anfrage senden',
    'form.sending': 'Wird gesendet…',
    'form.success': '✓ Ihre Anfrage wurde gesendet! Wir werden Sie in Kürze kontaktieren.',
    'form.error':   '✕ Etwas ist schiefgelaufen. Bitte versuche es erneut oder kontaktiere uns direkt.',
    'add.to.cart':  'In den Warenkorb',
    'badge.sale':   'Angebot',
    'added.toast':  'In den Warenkorb gelegt',
  },
};
